# Generated by Django 5.1.6 on 2025-06-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliderText', models.TextField(max_length=200, verbose_name='Slider Text')),
                ('sliderImage', models.FileField(upload_to='slider_images/')),
            ],
        ),
    ]
