# Generated by Django 5.1.6 on 2025-07-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_property_propertyfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='propertyFeature',
            field=models.CharField(choices=[('For Sell', 'For Sell'), ('For Rent', 'For Rent'), ('Sub-Let', 'Sub-Let')], max_length=50, verbose_name='feature Choice'),
        ),
    ]
