# Generated by Django 5.1.6 on 2025-07-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTestimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('statement', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='agent_profiles/')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
