# Generated by Django 5.1.6 on 2025-07-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_clienttestimony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttestimony',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='client_profiles/'),
        ),
    ]
