# Generated by Django 5.1.6 on 2025-07-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_clienttestimony_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_status',
            field=models.TextField(choices=[('Still Selling', 'Still Selling'), ('Taken', 'Taken'), ('Leased Out', 'Leased Out')], default=1, max_length=50, verbose_name='Property Status'),
            preserve_default=False,
        ),
    ]
