# Generated by Django 5.1.6 on 2025-07-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_propertyplan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyPlan',
            new_name='PropertyPaymentPlan',
        ),
    ]
