# Generated by Django 5.1.6 on 2025-07-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_propertysubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='allSubscription',
            field=models.CharField(default=1, max_length=50, verbose_name=[('Yes', 'Yes'), ('No', 'No')]),
            preserve_default=False,
        ),
    ]
