# Generated by Django 5.1.6 on 2025-07-09 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_property_allsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='allSubscription',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50),
        ),
        migrations.CreateModel(
            name='SubscriptionPropertyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_months', models.PositiveIntegerField(help_text='Enter duration in months (e.g. 4, 5, 9)')),
                ('initial_deposit_percent', models.PositiveIntegerField(default=30, help_text='e.g. 30 for 30% deposit')),
                ('initial_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='myapp.property')),
            ],
        ),
    ]
