# Generated by Django 5.1.6 on 2025-07-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_clientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedproduct',
            name='to_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
