# Generated by Django 5.1.6 on 2025-07-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedproduct',
            name='method',
            field=models.CharField(choices=[('Wallet', 'Wallet'), ('Paystack', 'Paystack')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
