# Generated by Django 5.1.6 on 2025-07-18 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='recipient',
        ),
    ]
