# Generated by Django 5.1.6 on 2025-07-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='auto_balance',
            field=models.BooleanField(default=False),
        ),
    ]
