# Generated by Django 5.1.6 on 2025-07-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_property_auto_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='auto_balance',
        ),
        migrations.AddField(
            model_name='propertysubscription',
            name='auto_balance',
            field=models.BooleanField(default=False),
        ),
    ]
