# Generated by Django 5.1.6 on 2025-07-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_remove_property_auto_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertysubscription',
            name='auto_balance',
        ),
        migrations.AddField(
            model_name='subscriptionpropertyplan',
            name='auto_balance',
            field=models.BooleanField(default=False),
        ),
    ]
