# Generated by Django 5.1.6 on 2025-07-19 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_propertysubscription_auto_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedProductTrash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('deposit', models.FloatField(blank=True, null=True)),
                ('to_balance', models.FloatField(blank=True, null=True)),
                ('date_removed', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
