# Generated by Django 5.1.6 on 2025-07-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_purchasedproducttrash'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpropertyplan',
            name='increase_every_n_months',
            field=models.PositiveIntegerField(blank=True, help_text='Apply increase every N months (e.g. 3)', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpropertyplan',
            name='increase_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage increase at each interval (e.g. 12 for 12%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpropertyplan',
            name='monthly_breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
