# Generated by Django 5.1.6 on 2025-07-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_subscriptionpropertyplan_increase_every_n_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpropertyplan',
            name='total_amount_payable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
