# Generated by Django 5.1.6 on 2025-07-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_subscriptionpropertyplan_total_amount_payable'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedproduct',
            name='Paidpercentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
