# Generated by Django 5.1.6 on 2025-07-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_purchasedproduct_paidpercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedproduct',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
    ]
