# Generated by Django 5.1.6 on 2025-07-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_uploadedcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
    ]
