# Generated by Django 5.1.6 on 2025-07-25 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_transaction_contract_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedproduct',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='myapp.property'),
        ),
    ]
