# Generated by Django 5.1.6 on 2025-07-25 21:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_purchasedproduct_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedproduct',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
