# Generated by Django 5.2.3 on 2025-07-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_withshirfreferral'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='referral_code',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
