# Generated by Django 5.2.3 on 2025-07-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_clientprofile_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='referral_code',
            field=models.CharField(),
        ),
    ]
