# Generated by Django 5.2.3 on 2025-07-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_alter_clientprofile_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='withshirfreferral',
            name='scheduled_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
