# Generated by Django 5.2.3 on 2025-07-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_withshirfreferral_scheduled_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='withshirfreferral',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withshirfreferral',
            name='paid_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withshirfreferral',
            name='recipient_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
