# Generated by Django 5.1.6 on 2025-07-30 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_event_galleryimage'),
        ('myapp', '0046_event_galleryimage'),
    ]

    operations = [
    ]
